page_title: Bogdan Angheluta - Nova Card
description: bogdanangheluta Nova Card profile
baseurl: /
url: https://bogdanangheluta.novacard.ro
avatar: avatar.jpeg
contact-first_name: Bogdan
contact-last_name: Angheluta
contact-title: Manager Proiect
contact-company: Nova Card
contact-email: bogdan@novacard.ro
contact-phone: +40758223215
contact-website: 
contact-facebook_url: https://www.facebook.com/bogdan.g.angheluta/
contact-linkedin_url: https://www.linkedin.com/in/anghelutabogdan
contact-instagram_url: 
contact-pinterest_url: 
contact-twitter_url: 
contact-youtube_url: 
contact-snapchat_url: 
contact-whatsapp_url: 
contact-tiktok_url: 
contact-telegram_url: 
contact-skype_url: 
contact-github_url: 
contact-gitlab_url: 
